module.exports = {
  "ALIVE_IMG": "",
  "FOOT": "ALEX MD",
  "PREFIX": ".",
  "AUTO_READ_STATUS": "false",
  "MODE": "private",
  "BOT_NUMBER": "917399805543",
  "OMDB_API_KEY": "76cb7f39",
  "READ_CMD": "false",
  "AUTO_VOICE": "false",
  "ANTI_BAD": "warn",
  "ANTI_BOT": "false",
  "ANTI_CALL": "false",
  "ANTI_LINK": "false",
  "ANTI_PHOTO": "warn",
  "ANTI_STICKER": "warn",
  "ANTI_DELETE": false,
  "DELETEMSGSENDTO": "917399805543",
  "ALWAYS_ONLINE": "false",
  "MOROCCO_BLOCK": "false",
  "OWNER_NAME": "ALEX MD",
  "OWNER_NUMBER": "917399805543",
  "AUTO_BIO": "false",
  "AUTO_TYPING": "false",
  "AUTO_RECORDING": "false",
  "WARN_COUNT": "3",
  "AI_MODE": false,
};
